# Generated by Django 4.2.9 on 2024-01-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('types', models.IntegerField()),
                ('amount', models.FloatField()),
                ('oldbalanceorig', models.FloatField()),
                ('newbalanceorig', models.FloatField()),
                ('oldbalancedest', models.FloatField()),
                ('newbalancedest', models.FloatField()),
                ('isflaggedfraud', models.FloatField()),
            ],
        ),
    ]
